name: Auto Assign Reviewers
on:
  pull_request:
    types: [opened, ready_for_review, reopened]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          reviewers: |
            DataDog/database-monitoring
          skipKeywords: wip, draft